FROM node:16-alpine
WORKDIR /usr/src/app

COPY package.json yarn.lock ./

RUN yarn install \
 && yarn cache clean \
 && apk del .build-deps

COPY . ./

RUN yarn build \
 && yarn bundle \
 && mkdir /data \
 && ln -s /data data

ENTRYPOINT ["yarn"]
